### ISSUE TITLE
Kotlin Coroutine 的一些探讨？

### ISSUE THREAD

**Issue by idisfkj** [VIPyinzhiwei/Eyepetizer#1]
Retrofit的请求返回Call<T>有点累赘，这样还要自己扩张.await方法。
```
@GET
fun getDaily(@Url url: String): Call<Daily>
```
直接返回Daily不香吗？
```
@GET
suspend fun getDaily(@Url url: String): Daily
```

Call + .await方法Retrofit已经有自己的实现了，可以直接拿来用

```
suspend fun <T : Any> Call<T>.await(): T {
  return suspendCancellableCoroutine { continuation ->
    continuation.invokeOnCancellation {
      cancel()
    }
    enqueue(object : Callback<T> {
      override fun onResponse(call: Call<T>, response: Response<T>) {
        if (response.isSuccessful) {
          val body = response.body()
          if (body == null) {
            val invocation = call.request().tag(Invocation::class.java)!!
            val method = invocation.method()
            val e = KotlinNullPointerException("Response from " +
                method.declaringClass.name +
                '.' +
                method.name +
                " was null but response body type was declared as non-null")
            continuation.resumeWithException(e)
          } else {
            continuation.resume(body)
          }
        } else {
          continuation.resumeWithException(HttpException(response))
        }
      }

      override fun onFailure(call: Call<T>, t: Throwable) {
        continuation.resumeWithException(t)
      }
    })
  }
}
```
我们要做的只是正常suspend block与try catch的异常处理

**Comment by VIPyinzhiwei** [comment]
收到，感谢老铁参与对 Kotlin Coroutine 的探讨~ 

关于以上提出的两点， 在 Retrofit 中对 Coroutines 的支持，其实是在 Retrofit 库升级 >= 2.6.0 开始支持的，它内置提供了对 Kotlin Coroutines 的支持。目前项目中 Retrofit 库引用的是最新的版本（ 2.6.1） ，并且自己手写了 await  函数，其目的是为了更好的帮助新手学习理解 Kotlin + 协程 + Retrofit 搭配使用等。

感谢理解与支持。

**Comment by VIPyinzhiwei** [comment]
> Retrofit的请求返回Call有点累赘，这样还要自己扩张.await方法。
> 
> ```
> @GET
> fun getDaily(@Url url: String): Call<Daily>
> ```
> 
> 直接返回Daily不香吗？
> 
> ```
> @GET
> suspend fun getDaily(@Url url: String): Daily
> ```
> 
> Call + .await方法Retrofit已经有自己的实现了，可以直接拿来用
> 
> ```
> suspend fun <T : Any> Call<T>.await(): T {
>   return suspendCancellableCoroutine { continuation ->
>     continuation.invokeOnCancellation {
>       cancel()
>     }
>     enqueue(object : Callback<T> {
>       override fun onResponse(call: Call<T>, response: Response<T>) {
>         if (response.isSuccessful) {
>           val body = response.body()
>           if (body == null) {
>             val invocation = call.request().tag(Invocation::class.java)!!
>             val method = invocation.method()
>             val e = KotlinNullPointerException("Response from " +
>                 method.declaringClass.name +
>                 '.' +
>                 method.name +
>                 " was null but response body type was declared as non-null")
>             continuation.resumeWithException(e)
>           } else {
>             continuation.resume(body)
>           }
>         } else {
>           continuation.resumeWithException(HttpException(response))
>         }
>       }
> 
>       override fun onFailure(call: Call<T>, t: Throwable) {
>         continuation.resumeWithException(t)
>       }
>     })
>   }
> }
> ```
> 
> 我们要做的只是正常suspend block与try catch的异常处理

收到，感谢老铁参与对Kotlin Coroutine的探讨〜

关于以上提出的两点，在Retrofit中对Coroutines的支持，其实是在Retrofit库升级> = 2.6.0开始支持的，它内置提供了对Kotlin Coroutines的支持。目前项目中Retrofit库引用的是最新的版本（2.6.1），和自己手写了await函数，其目的是为了更好的帮助新手学习理解Kotlin +协程+ Retrofit搭配使用等。

感谢理解与支持。
