### ISSUE TITLE
滑动的时候卡顿严重

### ISSUE THREAD

**Issue by Crazy-MT** [VIPyinzhiwei/Eyepetizer#10]

**Comment by Crazy-MT** [comment]
目前在华为mate 30、荣耀 10 、小米 8 ，均出现滑动卡顿现象。凡是 RecyclerView 的都卡顿。
系统版本Android 9 、Android 10

**Comment by VIPyinzhiwei** [comment]
> 目前在华为mate 30、荣耀 10 、小米 8 ，均出现滑动卡顿现象。凡是 RecyclerView 的都卡顿。
> 系统版本Android 9 、Android 10

好的，谢谢。另外有一个可能潜在的原因是：在 RecyclerView 列表上拉滚动的时候，由于网络信号偏差，导致在上拉加载时，正在请求数据，而 UI 上没有任何提示，一直在等待，所以可能会误认为 RecyclerView 存在卡顿现象。

目前官方新版本的「开眼」已经更新了列表上拉加载提示，后续有空了我再整理优化一下。

**Comment by Crazy-MT** [comment]
不客气。
已加载完的列表滑动的时候也是卡，我觉得跟网络无关。

**Comment by ram16g** [comment]
我找到了卡顿的原因，我自己的项目已经解决了卡顿的问题，有空的话我提交一个pr

**Comment by ram16g** [comment]
造成卡顿的原因是，自定义的 typefaceTextView每次都要重新加载字体文件，我的做法是在 application里面加载一次，然后全局使用

**Comment by VIPyinzhiwei** [comment]
@ram16g 问题已修复。 给每个 Typeface 变量加上对应的赋值就好了~

**Comment by ram16g** [comment]
@VIPyinzhiwei 是的，这样修改以后，丝般顺滑，感谢  :）
