### ISSUE TITLE
视频点击全屏后，再次点击全屏按钮退出全屏，第三次点击全屏按钮时不能横屏

### ISSUE THREAD

**Issue by SkyD666** [VIPyinzhiwei/Eyepetizer#15]

**Comment by VIPyinzhiwei** [comment]
@SkyD666 收到。感谢~

**Comment by SkyD666** [comment]
之前研究了一下，虽然具体原因未知，但是可以将Activity继承GSYBaseActivityDetail这个类，然后根据GSYVideoPlayer给的demo的写法，可以解决这个问题

**Comment by VIPyinzhiwei** [comment]
> 这可能是一种解决办法，但应该不是最好的~ 

后面等有空了处理下：）

**Comment by VIPyinzhiwei** [comment]
这可能是一种解决办法，但应该不是最好的~

后面等有空了处理下：）

**Comment by VIPyinzhiwei** [comment]
@SkyD666 切换全屏显示问题，已修复。
