### ISSUE TITLE
友盟的maven仓库地址变了

### ISSUE THREAD

**Issue by EvanEvil** [VIPyinzhiwei/Eyepetizer#16]
新的仓库地址改为：maven { url 'https://repo1.maven.org/maven2/' }

友盟文档：https://developer.umeng.com/docs/119267/detail/118584

**Comment by EvanEvil** [comment]
// 友盟统计SDK
    implementation  'com.umeng.umsdk:common:9.3.8'// 必选
    implementation  'com.umeng.umsdk:asms:1.2.2'// 必选

**Comment by VIPyinzhiwei** [comment]
@EvanEvil 好勒，地址已更新~
