### ISSUE TITLE
【赞👍】项目学习问题，望不吝赐教

### ISSUE THREAD

**Issue by tzyGeneral** [VIPyinzhiwei/Eyepetizer#19]
在推荐页面，我想实现里面的刷新推荐功能，可否给予思路呢

**Comment by VIPyinzhiwei** [comment]
@tzyGeneral 感谢提问。

思路其实很简单：只要能拿到新的推荐数据，将原来旧的几条数据替换下，再绑定到页面上即可。

如何获取新的推荐数据？可以在【推荐】页面抓个包看看，里面返回的数据提供了一个 refreshUrl 字段，通过这个字段，每次请求都能拿到新的推荐数据。
