### ISSUE TITLE
只能向下翻10条的Bug

### ISSUE THREAD

**Issue by AmazingMachine** [VIPyinzhiwei/Eyepetizer#2]
测试设备pixel xl android 10
在社区>>推荐>>点击图片预览大图后只能向下滑动翻10页没有下一个10条分页的加载
我测试了一下开眼原版app是有这个功能的，没事只是反馈一个测试信息，作者没必要开发的

备注
作者开发可见开发实力深厚，和隔壁那个开眼的Fullter版本在伯仲之间

**Comment by dudukee** [comment]
@AmazingMachine 请问方便发一下隔壁flutter版本的链接吗:smile:

**Comment by AmazingMachine** [comment]
> @AmazingMachine 请问方便发一下隔壁flutter版本的链接吗😄

发你邮箱了在这里发不合适

**Comment by VIPyinzhiwei** [comment]
> 测试设备pixel xl android 10
> 在社区>>推荐>>点击图片预览大图后只能向下滑动翻10页没有下一个10条分页的加载
> 我测试了一下开眼原版app是有这个功能的，没事只是反馈一个测试信息，作者没必要开发的
> 
> 备注
> 作者开发可见开发实力深厚，和隔壁那个开眼的Fullter版本在伯仲之间

目前社区-推荐列表点击 Item 跳转到详情界面（图片/视频查看器）后，滑动翻页数是根据社区-推荐列表 item 可见个数决定的。比如社区-推荐列表展示了 100 item，那么点击 Item 跳转到详情界面（图片/视频查看器），可以滑动翻 100 页。

感谢老铁提出的测试反馈，后期会考虑针对这个进行功能优化。

**Comment by wuzhaohui026** [comment]
> > @AmazingMachine 请问方便发一下隔壁flutter版本的链接吗😄
> 
> 发你邮箱了在这里发不合适

同求

**Comment by AmazingMachine** [comment]
> > 测试设备pixel xl android 10
> > 在社区>>推荐>>点击图片预览大图后只能向下滑动翻10页没有下一个10条分页的加载
> > 我测试了一下开眼原版app是有这个功能的，没事只是反馈一个测试信息，作者没必要开发的
> > 备注
> > 作者开发可见开发实力深厚，和隔壁那个开眼的Fullter版本在伯仲之间
> 
> 目前社区-推荐列表点击 Item 跳转到详情界面（图片/视频查看器）后，滑动翻页数是根据社区-推荐列表 item 可见个数决定的。比如社区-推荐列表展示了 100 item，那么点击 Item 跳转到详情界面（图片/视频查看器），可以滑动翻 100 页。
> 
> 感谢老铁提出的测试反馈，后期会考虑针对这个进行功能优化。

相对于item的数量是可以在接口反馈数据的时候自定义的，明白了
