### ISSUE TITLE
搜索接口

### ISSUE THREAD

**Issue by modifyFun** [VIPyinzhiwei/Eyepetizer#20]
大佬，我想问一下搜索的接口是什么呢？还有actionURL是什么呀？

**Comment by VIPyinzhiwei** [comment]
@modifyFun 感谢提问，

1、搜索接口是什么？

api/v3/search?query=搜索关键词

如果需要翻页查看更多搜索结果，需要另外加上 start 和 num 两个请求参数。另外可以自己尝试抓包看看，可以发现更多项目中没有使用到的 API ~

2、actionURL 是什么？

目前主要用来标识不同功能页面之间的跳转。也可以看看项目源码，里面有相关处理示例。
