### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [VIPyinzhiwei/Eyepetizer#24]
请问是否可以将应用发布到 F-Droid？Readme 中有一个非商业限制，请问是对代码的限制还是对数据的免责声明？谢谢！

**Comment by VIPyinzhiwei** [comment]
@linsui 感谢提问。项目代码只要遵守 Apache License 2.0 协议是可以任意使用的。“所有数据来源于开眼，仅供学习和交流使用，严禁用于任何商业用途，原作公司拥有所有权利。” 这句话是一个附加的补充说明，作为一个友情提醒哈。

**Comment by linsui** [comment]
谢谢！我稍后打包提交。
