### ISSUE TITLE
当我保持targetSdkVersion 32，会出现INSTALL_PARSE_FAILED_MANIFEST_MALFORMED错误，改成targetSdkVersion 30会立刻正常，这是怎么回事呢？

### ISSUE THREAD

**Issue by LouisLou2** [VIPyinzhiwei/Eyepetizer#28]

**Comment by VIPyinzhiwei** [comment]
问题已修复，代码已提交至develop分支。

出现这个问题的原因：由于第三方库 com.squareup.leakcanary:leakcanary-android:2.4 里的 LeakLauncherActivity类，未明确指定 android:exported 属性。这个属性的规定是从 Android12  也就是 targetSdkVersion > 30 开始的。
