### ISSUE TITLE
问一下

### ISSUE THREAD

**Issue by qzqs** [VIPyinzhiwei/Eyepetizer#3]
ERROR: Could not find method buildFeatures() for arguments [build_8ks6wbd6k3c8c8neyqccwgmi2$_run_closure1$_closure7@7ce812fd] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.
出现这个错误是我AS必须要升级成4.0.0才可以的么？

**Comment by VIPyinzhiwei** [comment]
> ERROR: Could not find method buildFeatures() for arguments [build_8ks6wbd6k3c8c8neyqccwgmi2$_run_closure1$_closure7@7ce812fd] on object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.
> 出现这个错误是我AS必须要升级成4.0.0才可以的么？

buildFeatures 这是 Android Gradle 插件 4.0.0 中的新功能，在 4.0.0 以下，您可以使用 dataBinding 代替。

参考链接：https://developer.android.com/studio/preview/features?hl=zh-cn

**Comment by qzqs** [comment]
Process: com.eyepetizer.android, PID: 22707
    java.lang.VerifyError: Verifier rejected class com.eyepetizer.android.logic.MainPageRepository: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestCommunityRecommend(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestCommunityRecommend(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
     java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestDaily(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestDaily(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
     java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestDiscovery(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestDiscovery(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
     java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestFollow(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestFollow(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
     java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestHomePageRecommend(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestHomePageRecommend(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
     java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestPushMessage(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestPushMessage(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef (declaration of 'com.eyepetizer.android.logic.MainPageRepository' appears in /data/app/com.eyepetizer.android-cbJC6zSVzWY9QPZ12ZBsJg==/base.apk!classes2.dex)
        at com.eyepetizer.android.util.InjectorUtil.getMainPageRepository(InjectorUtil.kt:38)
        at com.eyepetizer.android.util.InjectorUtil.getDiscoveryViewModelFactory(InjectorUtil.kt:42)
        at com.eyepetizer.android.ui.home.discovery.DiscoveryFragment$viewModel$2.invoke(DiscoveryFragment.kt:46)
        at com.eyepetizer.android.ui.home.discovery.DiscoveryFragment$viewModel$2.invoke(DiscoveryFragment.kt:44)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.eyepetizer.android.ui.home.discovery.DiscoveryFragment.getViewModel(Unknown Source:7)
        at com.eyepetizer.android.ui.home.discovery.DiscoveryFragment.onActivityCreated(DiscoveryFragment.kt:56)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717)
        at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:336)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1186)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
2020-07-08 12:12:54.889 22707-22707/com.eyepetizer.android E/AndroidRuntime:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1816)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
        at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:341)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:276)
        at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67)
        at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7773)
        at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:867)
        at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8808)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8766)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8754)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1645)

红米K30，打开软件就崩了..

**Comment by VIPyinzhiwei** [comment]
> Process: com.eyepetizer.android, PID: 22707
> java.lang.VerifyError: Verifier rejected class com.eyepetizer.android.logic.MainPageRepository: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestCommunityRecommend(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestCommunityRecommend(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
> java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestDaily(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestDaily(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
> java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestDiscovery(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestDiscovery(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
> java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestFollow(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestFollow(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
> java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestHomePageRecommend(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestHomePageRecommend(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef
> java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestPushMessage(java.lang.String, kotlin.coroutines.Continuation) failed to verify: java.lang.Object com.eyepetizer.android.logic.MainPageRepository.requestPushMessage(java.lang.String, kotlin.coroutines.Continuation): [0x9] register v4 has type Precise Reference: java.lang.String but expected Precise Reference: kotlin.jvm.internal.Ref$ObjectRef (declaration of 'com.eyepetizer.android.logic.MainPageRepository' appears in /data/app/com.eyepetizer.android-cbJC6zSVzWY9QPZ12ZBsJg==/base.apk!classes2.dex)
> at com.eyepetizer.android.util.InjectorUtil.getMainPageRepository(InjectorUtil.kt:38)
> at com.eyepetizer.android.util.InjectorUtil.getDiscoveryViewModelFactory(InjectorUtil.kt:42)
> at com.eyepetizer.android.ui.home.discovery.DiscoveryFragment$viewModel$2.invoke(DiscoveryFragment.kt:46)
> at com.eyepetizer.android.ui.home.discovery.DiscoveryFragment$viewModel$2.invoke(DiscoveryFragment.kt:44)
> at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
> at com.eyepetizer.android.ui.home.discovery.DiscoveryFragment.getViewModel(Unknown Source:7)
> at com.eyepetizer.android.ui.home.discovery.DiscoveryFragment.onActivityCreated(DiscoveryFragment.kt:56)
> at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2717)
> at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:336)
> at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1186)
> at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1354)
> at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1432)
> at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
> 2020-07-08 12:12:54.889 22707-22707/com.eyepetizer.android E/AndroidRuntime: at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
> at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
> at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
> at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1816)
> at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
> at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:341)
> at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:276)
> at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67)
> at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7773)
> at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:867)
> at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
> at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8808)
> at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8766)
> at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8754)
> at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1645)
> 
> 红米K30，打开软件就崩了..

关于部分机型在使用过程中出现的软件崩溃问题，目前全部都上传到后台的友盟统计里面了。下个版本会进行统一处理，感谢提出问题反馈！
