### ISSUE TITLE
能否加个文件上传下载示例模块？

### ISSUE THREAD

**Issue by mrcoderzou** [VIPyinzhiwei/Eyepetizer#4]
大神你好，我最近正在学习kotlin，正好看到了你的这个项目，我想请问下能不能加一个文件上传和下载的示例模块？

**Comment by VIPyinzhiwei** [comment]
后期版本迭代的时候会加入一些新的功能。比如缓存视频、观看记录、保存图片等。不过可能要等一段时间了，这段时间比较忙。

感谢关注与支持！

**Comment by VIPyinzhiwei** [comment]
> 大神你好，我最近正在学习kotlin，正好看到了你的这个项目，我想请问下能不能加一个文件上传和下载的示例模块？

后期版本迭代的时候会加入一些新的功能。比如缓存视频、观看记录、保存图片等。不过可能要等一段时间了，这段时间比较忙。

感谢关注与支持！

**Comment by mrcoderzou** [comment]
好的，多谢了！
