### ISSUE TITLE
请问图片红色标记的东西为什么这么做

### ISSUE THREAD

**Issue by wangtao2855** [VIPyinzhiwei/Eyepetizer#7]
![image](https://user-images.githubusercontent.com/34060120/87293652-361c8a00-c535-11ea-9b6c-845ea34ed5bc.png)
 我有点不太明白这里 Result.success 这都是啥

**Comment by VIPyinzhiwei** [comment]
> ![image](https://user-images.githubusercontent.com/34060120/87293652-361c8a00-c535-11ea-9b6c-845ea34ed5bc.png)
> 我有点不太明白这里 Result.success 这都是啥

通过调用 Android Jetpack 提供的 Android KTX 扩展程序（androidx.lifecycle:lifecycle-livedata-ktx），简化了将协程与 LiveData 一起使用，通过 emit(value)  将 LiveData 的值设置为给定的 value。

参考资料：
1、https://developer.android.com/topic/libraries/architecture/coroutines#lifecyclescope
2、LiveDataScope.kt 源码
