### ISSUE TITLE
SharedPreferences扩展可删除

### ISSUE THREAD

**Issue by MoonLoong** [VIPyinzhiwei/Eyepetizer#8]
既然使用了androidx.core:core-ktx ，里面已经包含SharedPreferences扩展，没必要将源码拷贝一份写个扩展方法，
![40E58954-A56C-43B3-BD35-814244C34EC5](https://user-images.githubusercontent.com/20401331/88045417-11ea2a00-cb81-11ea-9477-d28cc524a500.png)
修改如下：

![image](https://user-images.githubusercontent.com/20401331/88045714-8c1aae80-cb81-11ea-9972-21169bc7b53f.png)
需要在build.gradle中添加
![image](https://user-images.githubusercontent.com/20401331/88045785-aa80aa00-cb81-11ea-9e85-d033c7efb0b3.png)
这样SharedPreferences扩展即可删除

**Comment by VIPyinzhiwei** [comment]
> 既然使用了androidx.core:core-ktx ，里面已经包含SharedPreferences扩展，没必要将源码拷贝一份写个扩展方法，
> ![40E58954-A56C-43B3-BD35-814244C34EC5](https://user-images.githubusercontent.com/20401331/88045417-11ea2a00-cb81-11ea-9477-d28cc524a500.png)
> 修改如下：
> 
> ![image](https://user-images.githubusercontent.com/20401331/88045714-8c1aae80-cb81-11ea-9972-21169bc7b53f.png)
> 需要在build.gradle中添加
> ![image](https://user-images.githubusercontent.com/20401331/88045785-aa80aa00-cb81-11ea-9e85-d033c7efb0b3.png)
> 这样SharedPreferences扩展即可删除

好的，感谢提醒。Android KTX 固然很香，但是依然无法满足所有需求，这里更侧重于对扩展函数的学习应用，掌握了扩展函数的使用，就不再局限于 Android KTX 仅有的扩展 api 了，自己写的不是更香么？- -!
